server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG

### JWT Configuration
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000

spring:
  cloud:
    gateway:
      default-filters:
        - name: PreserveHostHeader
      httpclient:
        response-timeout: 10s
      forwarded-error-enabled: false
