spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/auth/**

server:
  port: 8080

logging:
  level:
    org.springframework: DEBUG